arm_group_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
  gains:
    joint1: {p: 100.0, i: 0.01, d: 10.0}
    joint2: {p: 100.0, i: 0.01, d: 10.0}
    joint3: {p: 100.0, i: 0.01, d: 10.0}
    joint4: {p: 100.0, i: 0.01, d: 10.0}
  trajectory_joint_names: [joint1, joint2, joint3, joint4]
  state_publish_rate:  50
  action_monitor_rate: 10

gripper_group_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - g_joint_1



  gains:
    g_joint_1: {p: 20.0, i: 0.1, d: 0.0}


  trajectory_joint_names: [g_joint_1]
  state_publish_rate:  50
  action_monitor_rate: 10