robot_arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: 
    - joint1
    - joint2
    - joint3
    - joint4

  stop_trajectory_duration: 0.5
  state_publish_rate: 25
  action_monitor_rate: 10

hitbot_joint_group_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
    - joint1  
    - joint2  
    - joint3  
    - joint4  