#Instead of using TAB for indentation, use two spaces at the place of one TAB
#Controller to control robot arm joints
robot_arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: 
    - joint1
    - joint2
    - joint3
    - joint4

robot_joints_controller:
  type: "position_controllers/JointGroupPositionController"
  joints: 
    - joint1
    - joint2
    - joint3
    - joint4
    
#Controller to continuously publish joint states/positions
joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50